package com.zc.web.model;

import java.io.Serializable;
import java.util.Date;

public class DebtOptLog implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column debt_opt_log.id
     *
     * @mbggenerated Wed Jun 03 11:24:30 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column debt_opt_log.zone_id
     *
     * @mbggenerated Wed Jun 03 11:24:30 CST 2015
     */
    private String zoneId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column debt_opt_log.player_id
     *
     * @mbggenerated Wed Jun 03 11:24:30 CST 2015
     */
    private String playerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column debt_opt_log.type
     *
     * @mbggenerated Wed Jun 03 11:24:30 CST 2015
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column debt_opt_log.count
     *
     * @mbggenerated Wed Jun 03 11:24:30 CST 2015
     */
    private Integer count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column debt_opt_log.reason
     *
     * @mbggenerated Wed Jun 03 11:24:30 CST 2015
     */
    private String reason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column debt_opt_log.opt_time
     *
     * @mbggenerated Wed Jun 03 11:24:30 CST 2015
     */
    private Date optTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table debt_opt_log
     *
     * @mbggenerated Wed Jun 03 11:24:30 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column debt_opt_log.id
     *
     * @return the value of debt_opt_log.id
     *
     * @mbggenerated Wed Jun 03 11:24:30 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column debt_opt_log.id
     *
     * @param id the value for debt_opt_log.id
     *
     * @mbggenerated Wed Jun 03 11:24:30 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column debt_opt_log.zone_id
     *
     * @return the value of debt_opt_log.zone_id
     *
     * @mbggenerated Wed Jun 03 11:24:30 CST 2015
     */
    public String getZoneId() {
        return zoneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column debt_opt_log.zone_id
     *
     * @param zoneId the value for debt_opt_log.zone_id
     *
     * @mbggenerated Wed Jun 03 11:24:30 CST 2015
     */
    public void setZoneId(String zoneId) {
        this.zoneId = zoneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column debt_opt_log.player_id
     *
     * @return the value of debt_opt_log.player_id
     *
     * @mbggenerated Wed Jun 03 11:24:30 CST 2015
     */
    public String getPlayerId() {
        return playerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column debt_opt_log.player_id
     *
     * @param playerId the value for debt_opt_log.player_id
     *
     * @mbggenerated Wed Jun 03 11:24:30 CST 2015
     */
    public void setPlayerId(String playerId) {
        this.playerId = playerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column debt_opt_log.type
     *
     * @return the value of debt_opt_log.type
     *
     * @mbggenerated Wed Jun 03 11:24:30 CST 2015
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column debt_opt_log.type
     *
     * @param type the value for debt_opt_log.type
     *
     * @mbggenerated Wed Jun 03 11:24:30 CST 2015
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column debt_opt_log.count
     *
     * @return the value of debt_opt_log.count
     *
     * @mbggenerated Wed Jun 03 11:24:30 CST 2015
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column debt_opt_log.count
     *
     * @param count the value for debt_opt_log.count
     *
     * @mbggenerated Wed Jun 03 11:24:30 CST 2015
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column debt_opt_log.reason
     *
     * @return the value of debt_opt_log.reason
     *
     * @mbggenerated Wed Jun 03 11:24:30 CST 2015
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column debt_opt_log.reason
     *
     * @param reason the value for debt_opt_log.reason
     *
     * @mbggenerated Wed Jun 03 11:24:30 CST 2015
     */
    public void setReason(String reason) {
        this.reason = reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column debt_opt_log.opt_time
     *
     * @return the value of debt_opt_log.opt_time
     *
     * @mbggenerated Wed Jun 03 11:24:30 CST 2015
     */
    public Date getOptTime() {
        return optTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column debt_opt_log.opt_time
     *
     * @param optTime the value for debt_opt_log.opt_time
     *
     * @mbggenerated Wed Jun 03 11:24:30 CST 2015
     */
    public void setOptTime(Date optTime) {
        this.optTime = optTime;
    }
}