package com.zc.common.model;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class MenuExample extends BaseExample{

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table menu
	 * @ibatorgenerated  Tue Apr 20 11:16:38 CST 2010
	 */
	protected String orderByClause;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table menu
	 * @ibatorgenerated  Tue Apr 20 11:16:38 CST 2010
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table menu
	 * @ibatorgenerated  Tue Apr 20 11:16:38 CST 2010
	 */
	public MenuExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table menu
	 * @ibatorgenerated  Tue Apr 20 11:16:38 CST 2010
	 */
	protected MenuExample(MenuExample example) {
		this.orderByClause = example.orderByClause;
		this.oredCriteria = example.oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table menu
	 * @ibatorgenerated  Tue Apr 20 11:16:38 CST 2010
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table menu
	 * @ibatorgenerated  Tue Apr 20 11:16:38 CST 2010
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table menu
	 * @ibatorgenerated  Tue Apr 20 11:16:38 CST 2010
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table menu
	 * @ibatorgenerated  Tue Apr 20 11:16:38 CST 2010
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table menu
	 * @ibatorgenerated  Tue Apr 20 11:16:38 CST 2010
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table menu
	 * @ibatorgenerated  Tue Apr 20 11:16:38 CST 2010
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table menu
	 * @ibatorgenerated  Tue Apr 20 11:16:38 CST 2010
	 */
	public void clear() {
		oredCriteria.clear();
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table menu
	 * @ibatorgenerated  Tue Apr 20 11:16:38 CST 2010
	 */
	public static class Criteria {
		protected List<String> criteriaWithoutValue;
		protected List<Map<String, Object>> criteriaWithSingleValue;
		protected List<Map<String, Object>> criteriaWithListValue;
		protected List<Map<String, Object>> criteriaWithBetweenValue;

		protected Criteria() {
			super();
			criteriaWithoutValue = new ArrayList<String>();
			criteriaWithSingleValue = new ArrayList<Map<String, Object>>();
			criteriaWithListValue = new ArrayList<Map<String, Object>>();
			criteriaWithBetweenValue = new ArrayList<Map<String, Object>>();
		}

		public boolean isValid() {
			return criteriaWithoutValue.size() > 0 || criteriaWithSingleValue.size() > 0 || criteriaWithListValue.size() > 0 || criteriaWithBetweenValue.size() > 0;
		}

		public List<String> getCriteriaWithoutValue() {
			return criteriaWithoutValue;
		}

		public List<Map<String, Object>> getCriteriaWithSingleValue() {
			return criteriaWithSingleValue;
		}

		public List<Map<String, Object>> getCriteriaWithListValue() {
			return criteriaWithListValue;
		}

		public List<Map<String, Object>> getCriteriaWithBetweenValue() {
			return criteriaWithBetweenValue;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteriaWithoutValue.add(condition);
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			Map<String, Object> map = new HashMap<String, Object>();
			map.put("condition", condition);
			map.put("value", value);
			criteriaWithSingleValue.add(map);
		}

		protected void addCriterion(String condition, List<? extends Object> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property + " cannot be null or empty");
			}
			Map<String, Object> map = new HashMap<String, Object>();
			map.put("condition", condition);
			map.put("values", values);
			criteriaWithListValue.add(map);
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			List<Object> list = new ArrayList<Object>();
			list.add(value1);
			list.add(value2);
			Map<String, Object> map = new HashMap<String, Object>();
			map.put("condition", condition);
			map.put("values", list);
			criteriaWithBetweenValue.add(map);
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return this;
		}

		public Criteria andNameIsNull() {
			addCriterion("name is null");
			return this;
		}

		public Criteria andNameIsNotNull() {
			addCriterion("name is not null");
			return this;
		}

		public Criteria andNameEqualTo(String value) {
			addCriterion("name =", value, "name");
			return this;
		}

		public Criteria andNameNotEqualTo(String value) {
			addCriterion("name <>", value, "name");
			return this;
		}

		public Criteria andNameGreaterThan(String value) {
			addCriterion("name >", value, "name");
			return this;
		}

		public Criteria andNameGreaterThanOrEqualTo(String value) {
			addCriterion("name >=", value, "name");
			return this;
		}

		public Criteria andNameLessThan(String value) {
			addCriterion("name <", value, "name");
			return this;
		}

		public Criteria andNameLessThanOrEqualTo(String value) {
			addCriterion("name <=", value, "name");
			return this;
		}

		public Criteria andNameLike(String value) {
			addCriterion("name like", value, "name");
			return this;
		}

		public Criteria andNameNotLike(String value) {
			addCriterion("name not like", value, "name");
			return this;
		}

		public Criteria andNameIn(List<String> values) {
			addCriterion("name in", values, "name");
			return this;
		}

		public Criteria andNameNotIn(List<String> values) {
			addCriterion("name not in", values, "name");
			return this;
		}

		public Criteria andNameBetween(String value1, String value2) {
			addCriterion("name between", value1, value2, "name");
			return this;
		}

		public Criteria andNameNotBetween(String value1, String value2) {
			addCriterion("name not between", value1, value2, "name");
			return this;
		}

		public Criteria andCodeIsNull() {
			addCriterion("code is null");
			return this;
		}

		public Criteria andCodeIsNotNull() {
			addCriterion("code is not null");
			return this;
		}

		public Criteria andCodeEqualTo(String value) {
			addCriterion("code =", value, "code");
			return this;
		}

		public Criteria andCodeNotEqualTo(String value) {
			addCriterion("code <>", value, "code");
			return this;
		}

		public Criteria andCodeGreaterThan(String value) {
			addCriterion("code >", value, "code");
			return this;
		}

		public Criteria andCodeGreaterThanOrEqualTo(String value) {
			addCriterion("code >=", value, "code");
			return this;
		}

		public Criteria andCodeLessThan(String value) {
			addCriterion("code <", value, "code");
			return this;
		}

		public Criteria andCodeLessThanOrEqualTo(String value) {
			addCriterion("code <=", value, "code");
			return this;
		}

		public Criteria andCodeLike(String value) {
			addCriterion("code like", value, "code");
			return this;
		}

		public Criteria andCodeNotLike(String value) {
			addCriterion("code not like", value, "code");
			return this;
		}

		public Criteria andCodeIn(List<String> values) {
			addCriterion("code in", values, "code");
			return this;
		}

		public Criteria andCodeNotIn(List<String> values) {
			addCriterion("code not in", values, "code");
			return this;
		}

		public Criteria andCodeBetween(String value1, String value2) {
			addCriterion("code between", value1, value2, "code");
			return this;
		}

		public Criteria andCodeNotBetween(String value1, String value2) {
			addCriterion("code not between", value1, value2, "code");
			return this;
		}
		
		public Criteria andCodeLengthEqualTo(int value) {
			addCriterion("length(code) =", value, "code");
			return this;
		}

		public Criteria andUrlIsNull() {
			addCriterion("url is null");
			return this;
		}

		public Criteria andUrlIsNotNull() {
			addCriterion("url is not null");
			return this;
		}

		public Criteria andUrlEqualTo(String value) {
			addCriterion("url =", value, "url");
			return this;
		}

		public Criteria andUrlNotEqualTo(String value) {
			addCriterion("url <>", value, "url");
			return this;
		}

		public Criteria andUrlGreaterThan(String value) {
			addCriterion("url >", value, "url");
			return this;
		}

		public Criteria andUrlGreaterThanOrEqualTo(String value) {
			addCriterion("url >=", value, "url");
			return this;
		}

		public Criteria andUrlLessThan(String value) {
			addCriterion("url <", value, "url");
			return this;
		}

		public Criteria andUrlLessThanOrEqualTo(String value) {
			addCriterion("url <=", value, "url");
			return this;
		}

		public Criteria andUrlLike(String value) {
			addCriterion("url like", value, "url");
			return this;
		}

		public Criteria andUrlNotLike(String value) {
			addCriterion("url not like", value, "url");
			return this;
		}

		public Criteria andUrlIn(List<String> values) {
			addCriterion("url in", values, "url");
			return this;
		}

		public Criteria andUrlNotIn(List<String> values) {
			addCriterion("url not in", values, "url");
			return this;
		}

		public Criteria andUrlBetween(String value1, String value2) {
			addCriterion("url between", value1, value2, "url");
			return this;
		}

		public Criteria andUrlNotBetween(String value1, String value2) {
			addCriterion("url not between", value1, value2, "url");
			return this;
		}

		public Criteria andRightNameIsNull() {
			addCriterion("right_name is null");
			return this;
		}

		public Criteria andRightNameIsNotNull() {
			addCriterion("right_name is not null");
			return this;
		}

		public Criteria andRightNameEqualTo(String value) {
			addCriterion("right_name =", value, "rightName");
			return this;
		}

		public Criteria andRightNameNotEqualTo(String value) {
			addCriterion("right_name <>", value, "rightName");
			return this;
		}

		public Criteria andRightNameGreaterThan(String value) {
			addCriterion("right_name >", value, "rightName");
			return this;
		}

		public Criteria andRightNameGreaterThanOrEqualTo(String value) {
			addCriterion("right_name >=", value, "rightName");
			return this;
		}

		public Criteria andRightNameLessThan(String value) {
			addCriterion("right_name <", value, "rightName");
			return this;
		}

		public Criteria andRightNameLessThanOrEqualTo(String value) {
			addCriterion("right_name <=", value, "rightName");
			return this;
		}

		public Criteria andRightNameLike(String value) {
			addCriterion("right_name like", value, "rightName");
			return this;
		}

		public Criteria andRightNameNotLike(String value) {
			addCriterion("right_name not like", value, "rightName");
			return this;
		}

		public Criteria andRightNameIn(List<String> values) {
			addCriterion("right_name in", values, "rightName");
			return this;
		}

		public Criteria andRightNameNotIn(List<String> values) {
			addCriterion("right_name not in", values, "rightName");
			return this;
		}

		public Criteria andRightNameBetween(String value1, String value2) {
			addCriterion("right_name between", value1, value2, "rightName");
			return this;
		}

		public Criteria andRightNameNotBetween(String value1, String value2) {
			addCriterion("right_name not between", value1, value2, "rightName");
			return this;
		}

		public Criteria andIconIsNull() {
			addCriterion("icon is null");
			return this;
		}

		public Criteria andIconIsNotNull() {
			addCriterion("icon is not null");
			return this;
		}

		public Criteria andIconEqualTo(String value) {
			addCriterion("icon =", value, "icon");
			return this;
		}

		public Criteria andIconNotEqualTo(String value) {
			addCriterion("icon <>", value, "icon");
			return this;
		}

		public Criteria andIconGreaterThan(String value) {
			addCriterion("icon >", value, "icon");
			return this;
		}

		public Criteria andIconGreaterThanOrEqualTo(String value) {
			addCriterion("icon >=", value, "icon");
			return this;
		}

		public Criteria andIconLessThan(String value) {
			addCriterion("icon <", value, "icon");
			return this;
		}

		public Criteria andIconLessThanOrEqualTo(String value) {
			addCriterion("icon <=", value, "icon");
			return this;
		}

		public Criteria andIconLike(String value) {
			addCriterion("icon like", value, "icon");
			return this;
		}

		public Criteria andIconNotLike(String value) {
			addCriterion("icon not like", value, "icon");
			return this;
		}

		public Criteria andIconIn(List<String> values) {
			addCriterion("icon in", values, "icon");
			return this;
		}

		public Criteria andIconNotIn(List<String> values) {
			addCriterion("icon not in", values, "icon");
			return this;
		}

		public Criteria andIconBetween(String value1, String value2) {
			addCriterion("icon between", value1, value2, "icon");
			return this;
		}

		public Criteria andIconNotBetween(String value1, String value2) {
			addCriterion("icon not between", value1, value2, "icon");
			return this;
		}

		public Criteria andMenuOrderIsNull() {
			addCriterion("menu_order is null");
			return this;
		}

		public Criteria andMenuOrderIsNotNull() {
			addCriterion("menu_order is not null");
			return this;
		}

		public Criteria andMenuOrderEqualTo(Integer value) {
			addCriterion("menu_order =", value, "menuOrder");
			return this;
		}

		public Criteria andMenuOrderNotEqualTo(Integer value) {
			addCriterion("menu_order <>", value, "menuOrder");
			return this;
		}

		public Criteria andMenuOrderGreaterThan(Integer value) {
			addCriterion("menu_order >", value, "menuOrder");
			return this;
		}

		public Criteria andMenuOrderGreaterThanOrEqualTo(Integer value) {
			addCriterion("menu_order >=", value, "menuOrder");
			return this;
		}

		public Criteria andMenuOrderLessThan(Integer value) {
			addCriterion("menu_order <", value, "menuOrder");
			return this;
		}

		public Criteria andMenuOrderLessThanOrEqualTo(Integer value) {
			addCriterion("menu_order <=", value, "menuOrder");
			return this;
		}

		public Criteria andMenuOrderIn(List<Integer> values) {
			addCriterion("menu_order in", values, "menuOrder");
			return this;
		}

		public Criteria andMenuOrderNotIn(List<Integer> values) {
			addCriterion("menu_order not in", values, "menuOrder");
			return this;
		}

		public Criteria andMenuOrderBetween(Integer value1, Integer value2) {
			addCriterion("menu_order between", value1, value2, "menuOrder");
			return this;
		}

		public Criteria andMenuOrderNotBetween(Integer value1, Integer value2) {
			addCriterion("menu_order not between", value1, value2, "menuOrder");
			return this;
		}
	}
}