package com.zc.common.model;

import java.io.Serializable;

public class SecRight  extends BaseModel implements Serializable{

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column sec_right.id
	 * @ibatorgenerated  Wed Apr 21 13:14:51 CST 2010
	 */
	private Integer id;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column sec_right.type
	 * @ibatorgenerated  Wed Apr 21 13:14:51 CST 2010
	 */
	private Integer type;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column sec_right.module
	 * @ibatorgenerated  Wed Apr 21 13:14:51 CST 2010
	 */
	private String module;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column sec_right.name
	 * @ibatorgenerated  Wed Apr 21 13:14:51 CST 2010
	 */
	private String name;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column sec_right.descn
	 * @ibatorgenerated  Wed Apr 21 13:14:51 CST 2010
	 */
	private String descn;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table sec_right
	 * @ibatorgenerated  Wed Apr 21 13:14:51 CST 2010
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column sec_right.id
	 * @return  the value of sec_right.id
	 * @ibatorgenerated  Wed Apr 21 13:14:51 CST 2010
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column sec_right.id
	 * @param id  the value for sec_right.id
	 * @ibatorgenerated  Wed Apr 21 13:14:51 CST 2010
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column sec_right.type
	 * @return  the value of sec_right.type
	 * @ibatorgenerated  Wed Apr 21 13:14:51 CST 2010
	 */
	public Integer getType() {
		return type;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column sec_right.type
	 * @param type  the value for sec_right.type
	 * @ibatorgenerated  Wed Apr 21 13:14:51 CST 2010
	 */
	public void setType(Integer type) {
		this.type = type;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column sec_right.module
	 * @return  the value of sec_right.module
	 * @ibatorgenerated  Wed Apr 21 13:14:51 CST 2010
	 */
	public String getModule() {
		return module;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column sec_right.module
	 * @param module  the value for sec_right.module
	 * @ibatorgenerated  Wed Apr 21 13:14:51 CST 2010
	 */
	public void setModule(String module) {
		this.module = module;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column sec_right.name
	 * @return  the value of sec_right.name
	 * @ibatorgenerated  Wed Apr 21 13:14:51 CST 2010
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column sec_right.name
	 * @param name  the value for sec_right.name
	 * @ibatorgenerated  Wed Apr 21 13:14:51 CST 2010
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column sec_right.descn
	 * @return  the value of sec_right.descn
	 * @ibatorgenerated  Wed Apr 21 13:14:51 CST 2010
	 */
	public String getDescn() {
		return descn;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column sec_right.descn
	 * @param descn  the value for sec_right.descn
	 * @ibatorgenerated  Wed Apr 21 13:14:51 CST 2010
	 */
	public void setDescn(String descn) {
		this.descn = descn;
	}
}