package com.zc.common.model;

public class SecRole  extends BaseModel{
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column sec_role.id
     *
     * @ibatorgenerated Sat Apr 03 23:03:23 CST 2010
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column sec_role.name
     *
     * @ibatorgenerated Sat Apr 03 23:03:23 CST 2010
     */
    private String name;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column sec_role.descn
     *
     * @ibatorgenerated Sat Apr 03 23:03:23 CST 2010
     */
    private String descn;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column sec_role.id
     *
     * @return the value of sec_role.id
     *
     * @ibatorgenerated Sat Apr 03 23:03:23 CST 2010
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column sec_role.id
     *
     * @param id the value for sec_role.id
     *
     * @ibatorgenerated Sat Apr 03 23:03:23 CST 2010
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column sec_role.name
     *
     * @return the value of sec_role.name
     *
     * @ibatorgenerated Sat Apr 03 23:03:23 CST 2010
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column sec_role.name
     *
     * @param name the value for sec_role.name
     *
     * @ibatorgenerated Sat Apr 03 23:03:23 CST 2010
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column sec_role.descn
     *
     * @return the value of sec_role.descn
     *
     * @ibatorgenerated Sat Apr 03 23:03:23 CST 2010
     */
    public String getDescn() {
        return descn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column sec_role.descn
     *
     * @param descn the value for sec_role.descn
     *
     * @ibatorgenerated Sat Apr 03 23:03:23 CST 2010
     */
    public void setDescn(String descn) {
        this.descn = descn;
    }
}