package com.zc.common.model;

public class SecRoleRightKey  extends BaseModel{

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column sec_role_right.right_id
	 * @ibatorgenerated  Tue Apr 06 15:33:49 CST 2010
	 */
	private Integer rightId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column sec_role_right.role_id
	 * @ibatorgenerated  Tue Apr 06 15:33:49 CST 2010
	 */
	private Integer roleId;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column sec_role_right.right_id
	 * @return  the value of sec_role_right.right_id
	 * @ibatorgenerated  Tue Apr 06 15:33:49 CST 2010
	 */
	public Integer getRightId() {
		return rightId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column sec_role_right.right_id
	 * @param rightId  the value for sec_role_right.right_id
	 * @ibatorgenerated  Tue Apr 06 15:33:49 CST 2010
	 */
	public void setRightId(Integer rightId) {
		this.rightId = rightId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column sec_role_right.role_id
	 * @return  the value of sec_role_right.role_id
	 * @ibatorgenerated  Tue Apr 06 15:33:49 CST 2010
	 */
	public Integer getRoleId() {
		return roleId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column sec_role_right.role_id
	 * @param roleId  the value for sec_role_right.role_id
	 * @ibatorgenerated  Tue Apr 06 15:33:49 CST 2010
	 */
	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}
}