package com.zc.common.model;

import java.util.Date;

import org.apache.commons.lang.builder.ToStringBuilder;

public class SecUser  extends BaseModel{

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column sec_user.id
	 * @ibatorgenerated  Thu Apr 08 12:29:43 CST 2010
	 */
	private Integer id;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column sec_user.name
	 * @ibatorgenerated  Thu Apr 08 12:29:43 CST 2010
	 */
	private String name;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column sec_user.password
	 * @ibatorgenerated  Thu Apr 08 12:29:43 CST 2010
	 */
	private String password;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column sec_user.enabled
	 * @ibatorgenerated  Thu Apr 08 12:29:43 CST 2010
	 */
	private Boolean enabled;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column sec_user.accountnonexpired
	 * @ibatorgenerated  Thu Apr 08 12:29:43 CST 2010
	 */
	private Boolean accountnonexpired;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column sec_user.credentialsnonexpired
	 * @ibatorgenerated  Thu Apr 08 12:29:43 CST 2010
	 */
	private Boolean credentialsnonexpired;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column sec_user.accountnonlocked
	 * @ibatorgenerated  Thu Apr 08 12:29:43 CST 2010
	 */
	private Boolean accountnonlocked;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column sec_user.descn
	 * @ibatorgenerated  Thu Apr 08 12:29:43 CST 2010
	 */
	private String descn;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column sec_user.created_at
	 * @ibatorgenerated  Thu Apr 08 12:29:43 CST 2010
	 */
	private Date createdAt;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column sec_user.id
	 * @return  the value of sec_user.id
	 * @ibatorgenerated  Thu Apr 08 12:29:43 CST 2010
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column sec_user.id
	 * @param id  the value for sec_user.id
	 * @ibatorgenerated  Thu Apr 08 12:29:43 CST 2010
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column sec_user.name
	 * @return  the value of sec_user.name
	 * @ibatorgenerated  Thu Apr 08 12:29:43 CST 2010
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column sec_user.name
	 * @param name  the value for sec_user.name
	 * @ibatorgenerated  Thu Apr 08 12:29:43 CST 2010
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column sec_user.password
	 * @return  the value of sec_user.password
	 * @ibatorgenerated  Thu Apr 08 12:29:43 CST 2010
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column sec_user.password
	 * @param password  the value for sec_user.password
	 * @ibatorgenerated  Thu Apr 08 12:29:43 CST 2010
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column sec_user.enabled
	 * @return  the value of sec_user.enabled
	 * @ibatorgenerated  Thu Apr 08 12:29:43 CST 2010
	 */
	public Boolean getEnabled() {
		return enabled;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column sec_user.enabled
	 * @param enabled  the value for sec_user.enabled
	 * @ibatorgenerated  Thu Apr 08 12:29:43 CST 2010
	 */
	public void setEnabled(Boolean enabled) {
		this.enabled = enabled;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column sec_user.accountnonexpired
	 * @return  the value of sec_user.accountnonexpired
	 * @ibatorgenerated  Thu Apr 08 12:29:43 CST 2010
	 */
	public Boolean getAccountnonexpired() {
		return accountnonexpired;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column sec_user.accountnonexpired
	 * @param accountnonexpired  the value for sec_user.accountnonexpired
	 * @ibatorgenerated  Thu Apr 08 12:29:43 CST 2010
	 */
	public void setAccountnonexpired(Boolean accountnonexpired) {
		this.accountnonexpired = accountnonexpired;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column sec_user.credentialsnonexpired
	 * @return  the value of sec_user.credentialsnonexpired
	 * @ibatorgenerated  Thu Apr 08 12:29:43 CST 2010
	 */
	public Boolean getCredentialsnonexpired() {
		return credentialsnonexpired;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column sec_user.credentialsnonexpired
	 * @param credentialsnonexpired  the value for sec_user.credentialsnonexpired
	 * @ibatorgenerated  Thu Apr 08 12:29:43 CST 2010
	 */
	public void setCredentialsnonexpired(Boolean credentialsnonexpired) {
		this.credentialsnonexpired = credentialsnonexpired;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column sec_user.accountnonlocked
	 * @return  the value of sec_user.accountnonlocked
	 * @ibatorgenerated  Thu Apr 08 12:29:43 CST 2010
	 */
	public Boolean getAccountnonlocked() {
		return accountnonlocked;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column sec_user.accountnonlocked
	 * @param accountnonlocked  the value for sec_user.accountnonlocked
	 * @ibatorgenerated  Thu Apr 08 12:29:43 CST 2010
	 */
	public void setAccountnonlocked(Boolean accountnonlocked) {
		this.accountnonlocked = accountnonlocked;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column sec_user.descn
	 * @return  the value of sec_user.descn
	 * @ibatorgenerated  Thu Apr 08 12:29:43 CST 2010
	 */
	public String getDescn() {
		return descn;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column sec_user.descn
	 * @param descn  the value for sec_user.descn
	 * @ibatorgenerated  Thu Apr 08 12:29:43 CST 2010
	 */
	public void setDescn(String descn) {
		this.descn = descn;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column sec_user.created_at
	 * @return  the value of sec_user.created_at
	 * @ibatorgenerated  Thu Apr 08 12:29:43 CST 2010
	 */
	public Date getCreatedAt() {
		return createdAt;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column sec_user.created_at
	 * @param createdAt  the value for sec_user.created_at
	 * @ibatorgenerated  Thu Apr 08 12:29:43 CST 2010
	 */
	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public String toString(){
		return ToStringBuilder.reflectionToString(this);
	}
}