package com.zc.common.dao;

import com.zc.common.model.Menu;
import com.zc.common.model.MenuExample;

import java.util.List;

public interface MenuDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table menu
	 * @ibatorgenerated  Tue Apr 20 11:16:38 CST 2010
	 */
	int countByExample(MenuExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table menu
	 * @ibatorgenerated  Tue Apr 20 11:16:38 CST 2010
	 */
	int deleteByExample(MenuExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table menu
	 * @ibatorgenerated  Tue Apr 20 11:16:38 CST 2010
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table menu
	 * @ibatorgenerated  Tue Apr 20 11:16:38 CST 2010
	 */
	Integer insert(Menu record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table menu
	 * @ibatorgenerated  Tue Apr 20 11:16:38 CST 2010
	 */
	Integer insertSelective(Menu record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table menu
	 * @ibatorgenerated  Tue Apr 20 11:16:38 CST 2010
	 */
	List<Menu> selectByExample(MenuExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table menu
	 * @ibatorgenerated  Tue Apr 20 11:16:38 CST 2010
	 */
	Menu selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table menu
	 * @ibatorgenerated  Tue Apr 20 11:16:38 CST 2010
	 */
	int updateByExampleSelective(Menu record, MenuExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table menu
	 * @ibatorgenerated  Tue Apr 20 11:16:38 CST 2010
	 */
	int updateByExample(Menu record, MenuExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table menu
	 * @ibatorgenerated  Tue Apr 20 11:16:38 CST 2010
	 */
	int updateByPrimaryKeySelective(Menu record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table menu
	 * @ibatorgenerated  Tue Apr 20 11:16:38 CST 2010
	 */
	int updateByPrimaryKey(Menu record);
}