package com.zc.common.dao;

import com.zc.common.model.Menu;
import com.zc.common.model.MenuExample;

import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class MenuDAOImpl extends SqlMapClientDaoSupport implements MenuDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table menu
	 * @ibatorgenerated  Tue Apr 20 11:16:38 CST 2010
	 */
	public MenuDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table menu
	 * @ibatorgenerated  Tue Apr 20 11:16:38 CST 2010
	 */
	public int countByExample(MenuExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject("menu.ibatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table menu
	 * @ibatorgenerated  Tue Apr 20 11:16:38 CST 2010
	 */
	public int deleteByExample(MenuExample example) {
		int rows = getSqlMapClientTemplate().delete("menu.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table menu
	 * @ibatorgenerated  Tue Apr 20 11:16:38 CST 2010
	 */
	public int deleteByPrimaryKey(Integer id) {
		Menu key = new Menu();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete("menu.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table menu
	 * @ibatorgenerated  Tue Apr 20 11:16:38 CST 2010
	 */
	public Integer insert(Menu record) {
		Object newKey = getSqlMapClientTemplate().insert("menu.ibatorgenerated_insert", record);
		return (Integer) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table menu
	 * @ibatorgenerated  Tue Apr 20 11:16:38 CST 2010
	 */
	public Integer insertSelective(Menu record) {
		Object newKey = getSqlMapClientTemplate().insert("menu.ibatorgenerated_insertSelective", record);
		return (Integer) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table menu
	 * @ibatorgenerated  Tue Apr 20 11:16:38 CST 2010
	 */
	@SuppressWarnings("unchecked")
	public List<Menu> selectByExample(MenuExample example) {
		List<Menu> list = getSqlMapClientTemplate().queryForList("menu.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table menu
	 * @ibatorgenerated  Tue Apr 20 11:16:38 CST 2010
	 */
	public Menu selectByPrimaryKey(Integer id) {
		Menu key = new Menu();
		key.setId(id);
		Menu record = (Menu) getSqlMapClientTemplate().queryForObject("menu.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table menu
	 * @ibatorgenerated  Tue Apr 20 11:16:38 CST 2010
	 */
	public int updateByExampleSelective(Menu record, MenuExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("menu.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table menu
	 * @ibatorgenerated  Tue Apr 20 11:16:38 CST 2010
	 */
	public int updateByExample(Menu record, MenuExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("menu.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table menu
	 * @ibatorgenerated  Tue Apr 20 11:16:38 CST 2010
	 */
	public int updateByPrimaryKeySelective(Menu record) {
		int rows = getSqlMapClientTemplate().update("menu.ibatorgenerated_updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table menu
	 * @ibatorgenerated  Tue Apr 20 11:16:38 CST 2010
	 */
	public int updateByPrimaryKey(Menu record) {
		int rows = getSqlMapClientTemplate().update("menu.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table menu
	 * @ibatorgenerated  Tue Apr 20 11:16:38 CST 2010
	 */
	private static class UpdateByExampleParms extends MenuExample {
		private Object record;

		public UpdateByExampleParms(Object record, MenuExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}