package com.zc.common.dao;

import com.zc.common.model.SecRoleRightExample;
import com.zc.common.model.SecRoleRightKey;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class SecRoleRightDAOImpl extends SqlMapClientDaoSupport implements SecRoleRightDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sec_role_right
	 * @ibatorgenerated  Tue Apr 06 15:33:49 CST 2010
	 */
	public SecRoleRightDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sec_role_right
	 * @ibatorgenerated  Tue Apr 06 15:33:49 CST 2010
	 */
	public int countByExample(SecRoleRightExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject("sec_role_right.ibatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sec_role_right
	 * @ibatorgenerated  Tue Apr 06 15:33:49 CST 2010
	 */
	public int deleteByExample(SecRoleRightExample example) {
		int rows = getSqlMapClientTemplate().delete("sec_role_right.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sec_role_right
	 * @ibatorgenerated  Tue Apr 06 15:33:49 CST 2010
	 */
	public int deleteByPrimaryKey(SecRoleRightKey key) {
		int rows = getSqlMapClientTemplate().delete("sec_role_right.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sec_role_right
	 * @ibatorgenerated  Tue Apr 06 15:33:49 CST 2010
	 */
	public void insert(SecRoleRightKey record) {
		getSqlMapClientTemplate().insert("sec_role_right.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sec_role_right
	 * @ibatorgenerated  Tue Apr 06 15:33:49 CST 2010
	 */
	public void insertSelective(SecRoleRightKey record) {
		getSqlMapClientTemplate().insert("sec_role_right.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sec_role_right
	 * @ibatorgenerated  Tue Apr 06 15:33:49 CST 2010
	 */
	@SuppressWarnings("unchecked")
	public List<SecRoleRightKey> selectByExample(SecRoleRightExample example) {
		List<SecRoleRightKey> list = getSqlMapClientTemplate().queryForList("sec_role_right.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sec_role_right
	 * @ibatorgenerated  Tue Apr 06 15:33:49 CST 2010
	 */
	public int updateByExampleSelective(SecRoleRightKey record, SecRoleRightExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("sec_role_right.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sec_role_right
	 * @ibatorgenerated  Tue Apr 06 15:33:49 CST 2010
	 */
	public int updateByExample(SecRoleRightKey record, SecRoleRightExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("sec_role_right.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table sec_role_right
	 * @ibatorgenerated  Tue Apr 06 15:33:49 CST 2010
	 */
	private static class UpdateByExampleParms extends SecRoleRightExample {
		private Object record;

		public UpdateByExampleParms(Object record, SecRoleRightExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}