package com.zc.common.dao;

import com.zc.common.model.SecRoleRightExample;
import com.zc.common.model.SecRoleRightKey;
import java.util.List;

public interface SecRoleRightDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sec_role_right
	 * @ibatorgenerated  Tue Apr 06 15:33:49 CST 2010
	 */
	int countByExample(SecRoleRightExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sec_role_right
	 * @ibatorgenerated  Tue Apr 06 15:33:49 CST 2010
	 */
	int deleteByExample(SecRoleRightExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sec_role_right
	 * @ibatorgenerated  Tue Apr 06 15:33:49 CST 2010
	 */
	int deleteByPrimaryKey(SecRoleRightKey key);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sec_role_right
	 * @ibatorgenerated  Tue Apr 06 15:33:49 CST 2010
	 */
	void insert(SecRoleRightKey record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sec_role_right
	 * @ibatorgenerated  Tue Apr 06 15:33:49 CST 2010
	 */
	void insertSelective(SecRoleRightKey record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sec_role_right
	 * @ibatorgenerated  Tue Apr 06 15:33:49 CST 2010
	 */
	List<SecRoleRightKey> selectByExample(SecRoleRightExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sec_role_right
	 * @ibatorgenerated  Tue Apr 06 15:33:49 CST 2010
	 */
	int updateByExampleSelective(SecRoleRightKey record, SecRoleRightExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sec_role_right
	 * @ibatorgenerated  Tue Apr 06 15:33:49 CST 2010
	 */
	int updateByExample(SecRoleRightKey record, SecRoleRightExample example);
}