package com.zc.common.dao;

import java.util.List;

import com.zc.common.model.SecRight;
import com.zc.common.model.SecRightExample;

public interface SecRightDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sec_right
	 * @ibatorgenerated  Wed Apr 21 13:14:52 CST 2010
	 */
	int countByExample(SecRightExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sec_right
	 * @ibatorgenerated  Wed Apr 21 13:14:52 CST 2010
	 */
	int deleteByExample(SecRightExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sec_right
	 * @ibatorgenerated  Wed Apr 21 13:14:52 CST 2010
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sec_right
	 * @ibatorgenerated  Wed Apr 21 13:14:52 CST 2010
	 */
	Integer insert(SecRight record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sec_right
	 * @ibatorgenerated  Wed Apr 21 13:14:52 CST 2010
	 */
	Integer insertSelective(SecRight record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sec_right
	 * @ibatorgenerated  Wed Apr 21 13:14:52 CST 2010
	 */
	List<SecRight> selectByExample(SecRightExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sec_right
	 * @ibatorgenerated  Wed Apr 21 13:14:52 CST 2010
	 */
	SecRight selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sec_right
	 * @ibatorgenerated  Wed Apr 21 13:14:52 CST 2010
	 */
	int updateByExampleSelective(SecRight record, SecRightExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sec_right
	 * @ibatorgenerated  Wed Apr 21 13:14:52 CST 2010
	 */
	int updateByExample(SecRight record, SecRightExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sec_right
	 * @ibatorgenerated  Wed Apr 21 13:14:52 CST 2010
	 */
	int updateByPrimaryKeySelective(SecRight record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sec_right
	 * @ibatorgenerated  Wed Apr 21 13:14:52 CST 2010
	 */
	int updateByPrimaryKey(SecRight record);

	List<SecRight> getUserRights(String userName);
}