package com.zc.common.dao;

import com.zc.common.model.SecRight;
import com.zc.common.model.SecRightExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class SecRightDAOImpl extends SqlMapClientDaoSupport implements SecRightDAO {
	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sec_right
	 * @ibatorgenerated  Wed Apr 21 13:14:51 CST 2010
	 */
	public SecRightDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sec_right
	 * @ibatorgenerated  Wed Apr 21 13:14:52 CST 2010
	 */
	public int countByExample(SecRightExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject("sec_right.ibatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sec_right
	 * @ibatorgenerated  Wed Apr 21 13:14:52 CST 2010
	 */
	public int deleteByExample(SecRightExample example) {
		int rows = getSqlMapClientTemplate().delete("sec_right.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sec_right
	 * @ibatorgenerated  Wed Apr 21 13:14:52 CST 2010
	 */
	public int deleteByPrimaryKey(Integer id) {
		SecRight key = new SecRight();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete("sec_right.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sec_right
	 * @ibatorgenerated  Wed Apr 21 13:14:52 CST 2010
	 */
	public Integer insert(SecRight record) {
		Object newKey = getSqlMapClientTemplate().insert("sec_right.ibatorgenerated_insert", record);
		return (Integer) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sec_right
	 * @ibatorgenerated  Wed Apr 21 13:14:52 CST 2010
	 */
	public Integer insertSelective(SecRight record) {
		Object newKey = getSqlMapClientTemplate().insert("sec_right.ibatorgenerated_insertSelective", record);
		return (Integer) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sec_right
	 * @ibatorgenerated  Wed Apr 21 13:14:52 CST 2010
	 */
	@SuppressWarnings("unchecked")
	public List<SecRight> selectByExample(SecRightExample example) {
		List<SecRight> list = getSqlMapClientTemplate().queryForList("sec_right.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sec_right
	 * @ibatorgenerated  Wed Apr 21 13:14:52 CST 2010
	 */
	public SecRight selectByPrimaryKey(Integer id) {
		SecRight key = new SecRight();
		key.setId(id);
		SecRight record = (SecRight) getSqlMapClientTemplate().queryForObject("sec_right.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sec_right
	 * @ibatorgenerated  Wed Apr 21 13:14:52 CST 2010
	 */
	public int updateByExampleSelective(SecRight record, SecRightExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("sec_right.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sec_right
	 * @ibatorgenerated  Wed Apr 21 13:14:52 CST 2010
	 */
	public int updateByExample(SecRight record, SecRightExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("sec_right.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sec_right
	 * @ibatorgenerated  Wed Apr 21 13:14:52 CST 2010
	 */
	public int updateByPrimaryKeySelective(SecRight record) {
		int rows = getSqlMapClientTemplate().update("sec_right.ibatorgenerated_updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sec_right
	 * @ibatorgenerated  Wed Apr 21 13:14:52 CST 2010
	 */
	public int updateByPrimaryKey(SecRight record) {
		int rows = getSqlMapClientTemplate().update("sec_right.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table sec_right
	 * @ibatorgenerated  Wed Apr 21 13:14:52 CST 2010
	 */
	private static class UpdateByExampleParms extends SecRightExample {
		private Object record;

		public UpdateByExampleParms(Object record, SecRightExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}

	private static final long serialVersionUID = 6034962908897351273L;

	@SuppressWarnings("unchecked")
	public List<SecRight> getUserRights(String userName) {
		List<SecRight> list = getSqlMapClientTemplate().queryForList("sec_right.get_user_rights", userName);
		return list;
	}
}