package com.zc.common.dao;

import com.zc.common.model.SecRole;
import com.zc.common.model.SecRoleExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class SecRoleDAOImpl extends SqlMapClientDaoSupport implements SecRoleDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sec_role
     *
     * @ibatorgenerated Sat Apr 03 23:03:23 CST 2010
     */
    public SecRoleDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sec_role
     *
     * @ibatorgenerated Sat Apr 03 23:03:23 CST 2010
     */
    public int countByExample(SecRoleExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("sec_role.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sec_role
     *
     * @ibatorgenerated Sat Apr 03 23:03:23 CST 2010
     */
    public int deleteByExample(SecRoleExample example) {
        int rows = getSqlMapClientTemplate().delete("sec_role.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sec_role
     *
     * @ibatorgenerated Sat Apr 03 23:03:23 CST 2010
     */
    public int deleteByPrimaryKey(Integer id) {
        SecRole key = new SecRole();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("sec_role.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sec_role
     *
     * @ibatorgenerated Sat Apr 03 23:03:23 CST 2010
     */
    public Integer insert(SecRole record) {
        Object newKey = getSqlMapClientTemplate().insert("sec_role.ibatorgenerated_insert", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sec_role
     *
     * @ibatorgenerated Sat Apr 03 23:03:23 CST 2010
     */
    public Integer insertSelective(SecRole record) {
        Object newKey = getSqlMapClientTemplate().insert("sec_role.ibatorgenerated_insertSelective", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sec_role
     *
     * @ibatorgenerated Sat Apr 03 23:03:23 CST 2010
     */
    @SuppressWarnings("unchecked")
    public List<SecRole> selectByExample(SecRoleExample example) {
        List<SecRole> list = getSqlMapClientTemplate().queryForList("sec_role.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sec_role
     *
     * @ibatorgenerated Sat Apr 03 23:03:23 CST 2010
     */
    public SecRole selectByPrimaryKey(Integer id) {
        SecRole key = new SecRole();
        key.setId(id);
        SecRole record = (SecRole) getSqlMapClientTemplate().queryForObject("sec_role.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sec_role
     *
     * @ibatorgenerated Sat Apr 03 23:03:23 CST 2010
     */
    public int updateByExampleSelective(SecRole record, SecRoleExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("sec_role.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sec_role
     *
     * @ibatorgenerated Sat Apr 03 23:03:23 CST 2010
     */
    public int updateByExample(SecRole record, SecRoleExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("sec_role.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sec_role
     *
     * @ibatorgenerated Sat Apr 03 23:03:23 CST 2010
     */
    public int updateByPrimaryKeySelective(SecRole record) {
        int rows = getSqlMapClientTemplate().update("sec_role.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sec_role
     *
     * @ibatorgenerated Sat Apr 03 23:03:23 CST 2010
     */
    public int updateByPrimaryKey(SecRole record) {
        int rows = getSqlMapClientTemplate().update("sec_role.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table sec_role
     *
     * @ibatorgenerated Sat Apr 03 23:03:23 CST 2010
     */
    private static class UpdateByExampleParms extends SecRoleExample {
        private Object record;

        public UpdateByExampleParms(Object record, SecRoleExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}