package com.zc.common.dao;

import com.zc.common.model.SecUser;
import com.zc.common.model.SecUserExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class SecUserDAOImpl extends SqlMapClientDaoSupport implements SecUserDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sec_user
	 * @ibatorgenerated  Mon Apr 12 15:14:54 CST 2010
	 */
	public SecUserDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sec_user
	 * @ibatorgenerated  Mon Apr 12 15:14:54 CST 2010
	 */
	public int countByExample(SecUserExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject("sec_user.ibatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sec_user
	 * @ibatorgenerated  Mon Apr 12 15:14:54 CST 2010
	 */
	public int deleteByExample(SecUserExample example) {
		int rows = getSqlMapClientTemplate().delete("sec_user.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sec_user
	 * @ibatorgenerated  Mon Apr 12 15:14:54 CST 2010
	 */
	public int deleteByPrimaryKey(Integer id) {
		SecUser key = new SecUser();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete("sec_user.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sec_user
	 * @ibatorgenerated  Mon Apr 12 15:14:54 CST 2010
	 */
	public Integer insert(SecUser record) {
		Object newKey = getSqlMapClientTemplate().insert("sec_user.ibatorgenerated_insert", record);
		return (Integer) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sec_user
	 * @ibatorgenerated  Mon Apr 12 15:14:54 CST 2010
	 */
	public Integer insertSelective(SecUser record) {
		Object newKey = getSqlMapClientTemplate().insert("sec_user.ibatorgenerated_insertSelective", record);
		return (Integer) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sec_user
	 * @ibatorgenerated  Mon Apr 12 15:14:54 CST 2010
	 */
	@SuppressWarnings("unchecked")
	public List<SecUser> selectByExample(SecUserExample example) {
		List<SecUser> list = getSqlMapClientTemplate().queryForList("sec_user.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sec_user
	 * @ibatorgenerated  Mon Apr 12 15:14:54 CST 2010
	 */
	public SecUser selectByPrimaryKey(Integer id) {
		SecUser key = new SecUser();
		key.setId(id);
		SecUser record = (SecUser) getSqlMapClientTemplate().queryForObject("sec_user.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sec_user
	 * @ibatorgenerated  Mon Apr 12 15:14:54 CST 2010
	 */
	public int updateByExampleSelective(SecUser record, SecUserExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("sec_user.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sec_user
	 * @ibatorgenerated  Mon Apr 12 15:14:54 CST 2010
	 */
	public int updateByExample(SecUser record, SecUserExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("sec_user.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sec_user
	 * @ibatorgenerated  Mon Apr 12 15:14:54 CST 2010
	 */
	public int updateByPrimaryKeySelective(SecUser record) {
		int rows = getSqlMapClientTemplate().update("sec_user.ibatorgenerated_updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sec_user
	 * @ibatorgenerated  Mon Apr 12 15:14:54 CST 2010
	 */
	public int updateByPrimaryKey(SecUser record) {
		int rows = getSqlMapClientTemplate().update("sec_user.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table sec_user
	 * @ibatorgenerated  Mon Apr 12 15:14:54 CST 2010
	 */
	private static class UpdateByExampleParms extends SecUserExample {
		private Object record;

		public UpdateByExampleParms(Object record, SecUserExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}