package com.zc.common.dao;

import com.zc.common.model.SecUser;
import com.zc.common.model.SecUserExample;
import java.util.List;

public interface SecUserDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sec_user
	 * @ibatorgenerated  Mon Apr 12 15:14:54 CST 2010
	 */
	int countByExample(SecUserExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sec_user
	 * @ibatorgenerated  Mon Apr 12 15:14:54 CST 2010
	 */
	int deleteByExample(SecUserExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sec_user
	 * @ibatorgenerated  Mon Apr 12 15:14:54 CST 2010
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sec_user
	 * @ibatorgenerated  Mon Apr 12 15:14:54 CST 2010
	 */
	Integer insert(SecUser record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sec_user
	 * @ibatorgenerated  Mon Apr 12 15:14:54 CST 2010
	 */
	Integer insertSelective(SecUser record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sec_user
	 * @ibatorgenerated  Mon Apr 12 15:14:54 CST 2010
	 */
	List<SecUser> selectByExample(SecUserExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sec_user
	 * @ibatorgenerated  Mon Apr 12 15:14:54 CST 2010
	 */
	SecUser selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sec_user
	 * @ibatorgenerated  Mon Apr 12 15:14:54 CST 2010
	 */
	int updateByExampleSelective(SecUser record, SecUserExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sec_user
	 * @ibatorgenerated  Mon Apr 12 15:14:54 CST 2010
	 */
	int updateByExample(SecUser record, SecUserExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sec_user
	 * @ibatorgenerated  Mon Apr 12 15:14:54 CST 2010
	 */
	int updateByPrimaryKeySelective(SecUser record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sec_user
	 * @ibatorgenerated  Mon Apr 12 15:14:54 CST 2010
	 */
	int updateByPrimaryKey(SecUser record);
}