package com.zc.common.dao;

import com.zc.common.model.SecUserRoleExample;
import com.zc.common.model.SecUserRoleKey;
import java.util.List;

public interface SecUserRoleDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sec_user_role
	 * @ibatorgenerated  Tue Apr 06 15:33:49 CST 2010
	 */
	int countByExample(SecUserRoleExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sec_user_role
	 * @ibatorgenerated  Tue Apr 06 15:33:49 CST 2010
	 */
	int deleteByExample(SecUserRoleExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sec_user_role
	 * @ibatorgenerated  Tue Apr 06 15:33:49 CST 2010
	 */
	int deleteByPrimaryKey(SecUserRoleKey key);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sec_user_role
	 * @ibatorgenerated  Tue Apr 06 15:33:49 CST 2010
	 */
	void insert(SecUserRoleKey record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sec_user_role
	 * @ibatorgenerated  Tue Apr 06 15:33:49 CST 2010
	 */
	void insertSelective(SecUserRoleKey record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sec_user_role
	 * @ibatorgenerated  Tue Apr 06 15:33:49 CST 2010
	 */
	List<SecUserRoleKey> selectByExample(SecUserRoleExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sec_user_role
	 * @ibatorgenerated  Tue Apr 06 15:33:49 CST 2010
	 */
	int updateByExampleSelective(SecUserRoleKey record, SecUserRoleExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sec_user_role
	 * @ibatorgenerated  Tue Apr 06 15:33:49 CST 2010
	 */
	int updateByExample(SecUserRoleKey record, SecUserRoleExample example);
}