package com.zc.common.dao;

import com.zc.common.model.SecUserRoleExample;
import com.zc.common.model.SecUserRoleKey;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class SecUserRoleDAOImpl extends SqlMapClientDaoSupport implements SecUserRoleDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sec_user_role
	 * @ibatorgenerated  Tue Apr 06 15:33:49 CST 2010
	 */
	public SecUserRoleDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sec_user_role
	 * @ibatorgenerated  Tue Apr 06 15:33:49 CST 2010
	 */
	public int countByExample(SecUserRoleExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject("sec_user_role.ibatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sec_user_role
	 * @ibatorgenerated  Tue Apr 06 15:33:49 CST 2010
	 */
	public int deleteByExample(SecUserRoleExample example) {
		int rows = getSqlMapClientTemplate().delete("sec_user_role.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sec_user_role
	 * @ibatorgenerated  Tue Apr 06 15:33:49 CST 2010
	 */
	public int deleteByPrimaryKey(SecUserRoleKey key) {
		int rows = getSqlMapClientTemplate().delete("sec_user_role.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sec_user_role
	 * @ibatorgenerated  Tue Apr 06 15:33:49 CST 2010
	 */
	public void insert(SecUserRoleKey record) {
		getSqlMapClientTemplate().insert("sec_user_role.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sec_user_role
	 * @ibatorgenerated  Tue Apr 06 15:33:49 CST 2010
	 */
	public void insertSelective(SecUserRoleKey record) {
		getSqlMapClientTemplate().insert("sec_user_role.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sec_user_role
	 * @ibatorgenerated  Tue Apr 06 15:33:49 CST 2010
	 */
	@SuppressWarnings("unchecked")
	public List<SecUserRoleKey> selectByExample(SecUserRoleExample example) {
		List<SecUserRoleKey> list = getSqlMapClientTemplate().queryForList("sec_user_role.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sec_user_role
	 * @ibatorgenerated  Tue Apr 06 15:33:49 CST 2010
	 */
	public int updateByExampleSelective(SecUserRoleKey record, SecUserRoleExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("sec_user_role.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sec_user_role
	 * @ibatorgenerated  Tue Apr 06 15:33:49 CST 2010
	 */
	public int updateByExample(SecUserRoleKey record, SecUserRoleExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("sec_user_role.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table sec_user_role
	 * @ibatorgenerated  Tue Apr 06 15:33:49 CST 2010
	 */
	private static class UpdateByExampleParms extends SecUserRoleExample {
		private Object record;

		public UpdateByExampleParms(Object record, SecUserRoleExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}