package com.zc.web.dao;

import com.zc.web.model.DebtOptLog;
import com.zc.web.model.DebtOptLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DebtOptLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table debt_opt_log
     *
     * @mbggenerated Wed Jun 03 11:24:30 CST 2015
     */
    int countByExample(DebtOptLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table debt_opt_log
     *
     * @mbggenerated Wed Jun 03 11:24:30 CST 2015
     */
    int deleteByExample(DebtOptLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table debt_opt_log
     *
     * @mbggenerated Wed Jun 03 11:24:30 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table debt_opt_log
     *
     * @mbggenerated Wed Jun 03 11:24:30 CST 2015
     */
    int insert(DebtOptLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table debt_opt_log
     *
     * @mbggenerated Wed Jun 03 11:24:30 CST 2015
     */
    int insertSelective(DebtOptLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table debt_opt_log
     *
     * @mbggenerated Wed Jun 03 11:24:30 CST 2015
     */
    List<DebtOptLog> selectByExample(DebtOptLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table debt_opt_log
     *
     * @mbggenerated Wed Jun 03 11:24:30 CST 2015
     */
    DebtOptLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table debt_opt_log
     *
     * @mbggenerated Wed Jun 03 11:24:30 CST 2015
     */
    int updateByExampleSelective(@Param("record") DebtOptLog record, @Param("example") DebtOptLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table debt_opt_log
     *
     * @mbggenerated Wed Jun 03 11:24:30 CST 2015
     */
    int updateByExample(@Param("record") DebtOptLog record, @Param("example") DebtOptLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table debt_opt_log
     *
     * @mbggenerated Wed Jun 03 11:24:30 CST 2015
     */
    int updateByPrimaryKeySelective(DebtOptLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table debt_opt_log
     *
     * @mbggenerated Wed Jun 03 11:24:30 CST 2015
     */
    int updateByPrimaryKey(DebtOptLog record);
}